package com.sds.orchestration.device.utils;

public enum WafTemplate {
	XPATH,
	HTTP_ACL,
	PATH_TRAVERSAL,
	SCAN_ANTI,
	XSS,
	DOWNLOAD_LIMIT,
	LDAP,
	INFO_LEAK,
	COMMAND_INJECT,
	SSI,
	WEB_SERVER_PLUGIN_ANTI,
	SQL_INJECT,
	HTTP_PROTOCOL_VALIDATION,
	REMOTE_FILE_INCLUSION,
	UPLOAD_LIMIT
}
